apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  namespace: monitoring
  labels:
    app: mongodb
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mongodb
  namespaceSelector:
    matchNames:
    - tech-challenge
  endpoints:
  - port: mongodb
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
