apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app
  namespace: tech-challenge
  labels:
    app: tech-challenge-app
spec:
  type: ClusterIP
  selector:
    app: tech-challenge-app
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  sessionAffinity: None
