apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: tech-challenge
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::054431466060:role/tech-challenge-external-secrets-sa
