apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tech-challenge

resources:
  - namespace.yaml
  - mongodb-secret.yaml
  - mongodb-configmap.yaml
  - mongodb-statefulset.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml
  - network-policy.yaml

commonLabels:
  project: tech-challenge
  managed-by: kustomize
