apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tech-challenge

resources:
  - namespace.yaml
  - mongodb-configmap.yaml
  - cluster-secretstore.yaml
  - mongodb-external-secret.yaml
  - mongodb-statefulset.yaml
  - mongodb-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-hpa.yaml
  - ingress.yaml
  - network-policy.yaml
  - poddisruptionbudget.yaml
  - resourcequota.yaml

commonLabels:
  project: tech-challenge
  managed-by: kustomize
