apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: tech-challenge
data:
  mongo-init.js: |
    db = db.getSiblingDB('tech_challenge');
    db.createCollection('visits');
    print('Database and collection created successfully');
