apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: tech-challenge
type: Opaque
stringData:
  # These are default values for local development
  # In production, use External Secrets Operator with AWS Secrets Manager
  username: admin
  password: changeme-in-production
