apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: tech-challenge
data:
  mongo-init.js: |
    db = db.getSiblingDB('tech_challenge');

    db.createCollection('visits');

    db.visits.insertOne({
      timestamp: new Date(),
      message: 'Database initialized successfully'
    });

    print('Database tech_challenge initialized with visits collection');
