apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tech-challenge-app-pdb
  namespace: tech-challenge
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: tech-challenge-app
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
  namespace: tech-challenge
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: mongodb
